name: typesense
on: [push]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Test
    runs-on: macos-latest
    steps:
      - run: brew update-reset "$(brew --repository)"
      - run: cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git pull || true
      - run: brew tap "$GITHUB_REPOSITORY"
      - run: brew update-reset "$(brew --repository "$GITHUB_REPOSITORY")"
      - run: brew install ankane/core/typesense --only-dependencies
      - run: brew install ankane/core/typesense -s --verbose || true
      - run: cat /Users/runner/Library/Logs/Homebrew/typesense/*
      - run: brew test ankane/core/typesense --verbose
      - run: brew audit --new-formula typesense
      - run: brew audit --strict typesense
