name: libpg_query
on: [push]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Test
    runs-on: macos-latest
    steps:
      - run: brew update-reset "$(brew --repository)"
      - run: cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git pull || true
      - run: brew tap "$GITHUB_REPOSITORY"
      - run: brew update-reset "$(brew --repository "$GITHUB_REPOSITORY")"
      - run: brew install ankane/core/libpg_query --only-dependencies
      - run: brew install ankane/core/libpg_query -s --verbose || true
      - run: cat /Users/runner/Library/Logs/Homebrew/libpg_query/*
      - run: brew test ankane/core/libpg_query --verbose
      - run: brew audit --new-formula libpg_query
      - run: brew audit --strict libpg_query
